export const
  ORIENTATION_PORTRAIT = 'portrait',
  ORIENTATION_LANDSCAPE = 'landscape',

  FETCH_QUESTIONS = 'FETCH_QUESTIONS',
  QUESTION_ANSWER_CHANGE = 'QUESTION_ANSWER_CHANGE',
  PREVIOUS_QUESTION = 'PREVIOUS_QUESTION',
  NEXT_QUESTION = 'NEXT_QUESTION',
  QUESTION_WEIGHTS = 'QUESTION_WEIGHTS',

  APPSTATE_LOADING = 'LOADING',
  APPSTATE_ERROR = 'ERROR',
  APPSTATE_OK = 'OK',
  
  QUIZ_RESULT_SCORE = 'QUIZ_RESULT_SCORE'
